/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;

import org.example.Calculator.Operation;

public class AppTest {

 // NOTE: How to make a test
 // @Test
 // public void appHasAGreeting() {
 // App classUnderTest = new App();
 // assertNotNull("app should have a greeting", classUnderTest.getGreeting());
 // }

 @Test
 public void setOperandsTest() {

  Calculator calculator = new Calculator();

  int a = 3;
  int b = 6;

  calculator.setLeftOperand(a);
  calculator.setRightOperand(b);

  assertEquals(a, calculator.getLeftOperand());
  assertEquals(b, calculator.getRightOperand());
 }

 @Test
 public void setOperatorsTest() {

  Calculator calculator = new Calculator();

  // calculator.setOperator(1); TODO: Test with numbers aswell?
  calculator.setOperator(Calculator.Operation.SUM);

  calculator.setLeftOperand(2);
  calculator.setRightOperand(3);

  calculator.ApplyOpperation();
  assertEquals(5, calculator.Result());
 }

 @Test
 public void sumTest() {
  Calculator calculator = new Calculator();

  int a = 5;
  int b = 8;

  calculator.setOperator(Operation.SUM);
  calculator.setLeftOperand(a);
  calculator.setRightOperand(b);
  calculator.ApplyOpperation();

  assertEquals(a + b, calculator.Result());
 }

 @Test
 public void multiplyTest() {
  Calculator calculator = new Calculator();

  int a = 4;
  int b = 4;

  calculator.setLeftOperand(a);
  calculator.setRightOperand(b);
  calculator.setOperator(Operation.MULTIPLY);
  calculator.ApplyOpperation();

  assertEquals(a * b, calculator.Result());
 }

 @Test
 public void powerTest() {

  Calculator calculator = new Calculator();

  int a = 2;
  int b = 5;

  calculator.setLeftOperand(a);
  calculator.setRightOperand(b);
  calculator.setOperator(Operation.POWER);
  calculator.ApplyOpperation();

  assertEquals(32, calculator.Result());
  // assertEquals(32, calculator.Result());
 }

 // @Test
 // public void squareRootOperation() {
 // Calculator calculator = new Calculator();
 // int a = 16;
 // calculator.sqrt(a);
 // assertEquals(4, calculator.result());
 // }
}
