/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {

 // NOTE: How to make a test
 // @Test
 // public void appHasAGreeting() {
 // App classUnderTest = new App();
 // assertNotNull("app should have a greeting", classUnderTest.getGreeting());
 // }

 @Test
 public void sumTest() {
  Calculator calculator = new Calculator();
  int a = 5;
  int b = 8;
  calculator.Sum(a, b);
  assertEquals(13, calculator.Result());
 }

 @Test
 public void multiplyTest() {
  Calculator calculator = new Calculator();
  int a = 4;
  int b = 4;
  calculator.Multiplicate(a, b);
  assertEquals(16, calculator.Result());
 }

 @Test
 public void powerTest() {
  Calculator calculator = new Calculator();
  int a = 2;
  int b = 5;
  calculator.Power(a, b);
  assertEquals(32, calculator.Result());
  // assertEquals(4, calculator.Result());
 }

 // @Test
 // public void squareRootOperation() {
 // Calculator calculator = new Calculator();
 // int a = 16;
 // calculator.sqrt(a);
 // assertEquals(4, calculator.result());
 // }
}
